### PR TITLE
fix: VP decimals

### LINKED ISSUE #1488: Trim VP decimals on B&T cards
Image

### PR DESCRIPTION
**Pull request by ncomerci**
**Screenshots**

### Before
image

### After
image

**Related Issue**
Closes #1488 

- [ ]  **Functionality validation**
    - [ ]  Feature working as described in the related issue
    - [ ]  New environment variables have been set
    - [ ]  New API services methods have tests
    - [ ]  Code errors are being logged in the code health service
- [ ]  **Product validation**
    - [ ]  UI changes look the same as in Figma
    - [ ]  Usage events are being sent to the product analytics service
    - [ ]  New common components have been documented in Storybook
    - [ ]  Preview link if it’s a customer facing issue
- [ ] **Documentation**
    - [ ] README updated
    - [ ] New API changes are documented
- [ ] **Accessibility**
    - [ ] UI changes are accessible

### CODE REVIEW

File: src/entities/Proposal/outcomeUtils.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export function calculateWinnerChoice(result: Scores) {
       }
       return winner
     })
-  const winnerVotingPower = result[winnerChoice]
+  const winnerVotingPower = Math.round(result[winnerChoice])
```
Comment (1emu) [inline src/entities/Proposal/outcomeUtils.ts:25]: why do you need to round here? I think we should try to use the exact numbers for calculating winner choice

**Review by 1emu — APPROVED** [review]

**Review by andyesp — APPROVED** [review]

File: src/entities/Proposal/outcomeUtils.ts (hunk 1 above)
Comment (ncomerci) [reply src/entities/Proposal/outcomeUtils.ts:25]: We are rounding the final result
