### PR TITLE
fix: Category card as link

### LINKED ISSUE #957: Category cards in grants should be a link
Image

We should render that as an `<a>` tag.

### PR DESCRIPTION
**Pull request by ncomerci**
This closes #957

### CODE REVIEW

File: src/components/GrantRequest/GrantRequestSectionCard.tsx [hunk 1]
```diff
@@ -15,25 +26,22 @@ export const GrantRequestSectionCard = ({
...
-  helper?: React.ReactNode
-  subtitleVariant?: 'normal' | 'uppercase'
-  error?: boolean
-  onClick?: () => void
-}) => {
+  href,
+}: Props) => {
   return (
-    <div
+    <a
```
Comment (andyesp) [inline src/components/GrantRequest/GrantRequestSectionCard.tsx:32]: Can't we use the <Link /> component? I think it's the one from `decentraland-gatsby`.

**Review by andyesp — APPROVED** [review]

File: src/components/Proposal/View/Budget/RequestedBudgetCard.tsx [hunk 2]
```diff
@@ -82,10 +82,11 @@ export default function RequestedBudgetCard({ proposal, budget }: Props) {
   }, [
     isProposalActive,
     allocatedCategoryBudget,
+    isOverBudget,
+    categoryBudget,
     requestedBudget,
     remainingBudgetDisplayed,
-    categoryBudget,
-    isOverBudget,
+    totalCategoryBudget,
```
Comment (1emu) [inline src/components/Proposal/View/Budget/RequestedBudgetCard.tsx:89]: Are `totalCategoryBudget` and `allocatedCategoryBudget` necesary in the deps if we already have `categoryBudget`?
