### PR TITLE
fix: Title attribute

### LINKED ISSUE #1515: Add title attr to SummaryContentItem_DescriptionText
This would allow for mouse-over interaction to display the complete title when title length exceeds max-width

Image

### PR DESCRIPTION
**Pull request by ncomerci**
**Screenshots**
image

**Related Issue**
Closes #1515 

- [ ]  **Functionality validation**
    - [ ]  Feature working as described in the related issue
    - [ ]  New environment variables have been set
    - [ ]  New API services methods have tests
    - [ ]  Code errors are being logged in the code health service
- [ ]  **Product validation**
    - [ ]  UI changes look the same as in Figma
    - [ ]  Usage events are being sent to the product analytics service
    - [ ]  New common components have been documented in Storybook
    - [ ]  Preview link if it’s a customer facing issue
- [ ] **Documentation**
    - [ ] README updated
    - [ ] New API changes are documented
- [ ] **Accessibility**
    - [ ] UI changes are accessible

### CODE REVIEW

**Review by 1emu — APPROVED** [review]

File: src/components/Common/Typography/Text.tsx [hunk 1]
```diff
@@ -21,23 +23,35 @@ interface Props {
...
-    `Text--size-${size}`,
-    `Text--weight-${weight}`,
-    `Text--color-${color}`,
-    `Text--style-${style}`,
-    className
-  )
-  const Component = as ?? 'p'
-  return <Component className={componentClassNames}>{children}</Component>
-}
+// eslint-disable-next-line react/display-name
```
Comment (andyesp) [inline src/components/Common/Typography/Text.tsx:26]: Or you could just add the display name.
`Text.displayName = "Text"`

**Review by andyesp — APPROVED** [review]
