### PR TITLE
fix: links not opening in new window

### LINKED ISSUE #1083: Enable ctrl+click affordance to open links in a new tab
At the moment there is no way of open a link in a new tab using ctrl+click from proposal or grants lists:
https://governance.decentraland.org/proposals/?type=hiring https://governance.decentraland.org/grants/
It works from the profile view: https://governance.decentraland.org/profile/?address=0x511a22cdd2c4ee8357bb02df2578037ffe8a4d8d

### PR DESCRIPTION
**Pull request by andyesp**
Closes #1083

### CODE REVIEW

File: src/components/Common/Typography/Link.tsx [hunk 1]
```diff
@@ -14,15 +18,19 @@ function isLocalLink(href?: string | null) {
   )
 }
 
+const TARGET_BLANK = '_blank'
+
 export default function Link({ target, rel, href, onClick, className, ...props }: Props) {
   const isLocal = isLocalLink(href)
-  const linkTarget = !target && !isLocal ? '_blank' : target || undefined
+  const linkTarget = !target && !isLocal ? TARGET_BLANK : target || undefined
```
Comment (1emu) [inline src/components/Common/Typography/Link.tsx:25]: This can also be written like
`const linkTarget = !isLocal ? target || TARGET_BLANK : undefined;`

File: src/components/Common/Typography/Link.tsx [hunk 2]
```diff
@@ -14,15 +18,19 @@ function isLocalLink(href?: string | null) {
...
   const linkRel = !isLocal ? classNames(rel, 'noopener', 'noreferrer') : rel
   const handleClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
     if (onClick) {
       onClick(e)
     }
-    if (isLocal && href) {
+
```
Comment (1emu) [inline src/components/Common/Typography/Link.tsx:31]: And for 10k more `onClick && onClick(e)` instead of the if

**Review by 1emu — APPROVED** [review]

File: src/components/Common/Typography/Link.tsx (hunk 2 above)
Comment (andyesp) [reply src/components/Common/Typography/Link.tsx:31]: I prefer the explicit if in this case

**Review by ncomerci — APPROVED** [review]
