### PR TITLE
fix: delegation, proposal updates and pills styles and improvements

### LINKED ISSUE #1079: Clicking on update on card in grants page navigates to proposal

### LINKED ISSUE #1080: Wrong chevron icon size in user avatar component dao delegates list
Image

Image

### LINKED ISSUE #1081: Pills position in proposals voted on component is wrong
Image

### PR DESCRIPTION
**Pull request by andyesp**
Closes #1081 
Closes #1079 
Closes #1080

### CODE REVIEW

File: src/components/Common/Pill.tsx [hunk 1]
```diff
@@ -25,13 +25,18 @@ export type Props = {
...
 
-const Pill = ({ children, size = 'default', style = 'shiny', color = PillColor.Green, className, icon }: Props) => {
+export default function Pill({
+  children,
+  size = 'default',
+  style = 'shiny',
+  color = PillColor.Green,
+  className,
+  icon,
+}: Props) {
```
Comment (1emu) [inline src/components/Common/Pill.tsx:35]: Pill prop `size` could also be `"sm" | "md"` instead of `"small" | "default"` 🐦

**Review by 1emu — APPROVED** [review]
