### PR TITLE
fix: profile proposals pagination

### LINKED ISSUE #1383: Profile is showing proposals of other users
### Reproduction steps

1. Log in
2. Go to a profile (not own) and wait for the proposals to load
3. Go to logged in user profile

### PR DESCRIPTION
**Pull request by andyesp**
**Related Issue**
Fixes #1383

- [x]  **Functionality validation**
    - [x]  Feature working as described in the related issue
- [x]  **Product validation**
    - [x]  UI changes look the same as in Figma
    - [x]  Preview link if it’s a customer facing issue

### CODE REVIEW

File: src/components/Common/FullWidthButton.tsx [hunk 1]
```diff
@@ -1,28 +1,38 @@
...
   children: React.ReactNode
   className?: string
-  link?: string
+  href?: string
   newWindow?: boolean
+  loading?: boolean
 }
 
-const FullWidthButton = ({ onClick, children, className, link, newWindow = false }: Props) => {
+// TODO: FullWidthButton should render Link when href is provided
```
Comment (ncomerci) [inline src/components/Common/FullWidthButton.tsx:16]: I think you can do:

```
<Button
  as={href ? Link : undefined}
  ...
/>
```

**Review by ncomerci — APPROVED** [review]

File: src/components/Common/FullWidthButton.tsx (hunk 1 above)
Comment (andyesp) [reply src/components/Common/FullWidthButton.tsx:16]: Definitely! I'll change it in another PR.

**Review by 1emu — APPROVED** [review]
