### PR TITLE
fix: snapshot status banner

### LINKED ISSUE #1318: fix snapshot status banner

### PR DESCRIPTION
**Pull request by 1emu**
Closes #1318 

Switched to error rate monitoring:

image

image

image

### CODE REVIEW

File: src/constants.ts [hunk 1]
```diff
@@ -38,4 +38,7 @@ export const DEBUG_ADDRESSES = (process.env.DEBUG_ADDRESSES || '')
   .split(',')
   .filter(isEthereumAddress)
   .map((address) => address.toLowerCase())
-export const SNAPSHOT_STATUS_ENABLED = false
+
+export const SNAPSHOT_STATUS_ENABLED = process.env.SNAPSHOT_STATUS_ENABLED === 'true'
```
Comment (andyesp) [inline src/constants.ts:42]: You can use `getBooleanStringVar`

File: src/services/SnapshotStatusService.ts [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+    if (errorRate > SNAPSHOT_STATUS_ERROR_RATE_THRESHOLD) {
+      health = ServiceHealth.Failing
+    }
+    return { errorRate, health }
+  }
+
+  private static visualizeRequestResults(requestResults: boolean[]) {
+    const numRows = 1
+    const numCols = requestResults.length
+    const greenPoint = chalk.green('●')
```
Comment (ncomerci) [inline src/services/SnapshotStatusService.ts:79]: Should we keep printing this?

**Review by ncomerci — APPROVED** [review]

File: src/services/SnapshotStatusService.ts (hunk 2 above)
Comment (1emu) [reply src/services/SnapshotStatusService.ts:79]: I don't see why not :) 
It will only appear in the logs when there are errors in the buffer, and it's useful to see how the errors are mixed with the OK requests

File: src/constants.ts (hunk 1 above)
Comment (1emu) [reply src/constants.ts:42]: I thought about it but it uses a clientEnv method that takes the var from config.json, I wasn't sure that I could use it in this case

Comment (andyesp) [reply src/constants.ts:42]: We can check this in another PR

**Review by andyesp — APPROVED** [review]

File: src/constants.ts (hunk 1 above)
Comment (1emu) [reply src/constants.ts:42]: https://github.com/decentraland/governance/issues/1328
