### PR TITLE
fix: Prioritized vesting on projects

### LINKED ISSUE #1578: Use last vesting contract available in projects dashboard

### PR DESCRIPTION
**Pull request by ncomerci**
**Related Issue**
This closes #1578 

- [ ]  **Functionality validation**
    - [ ]  Feature working as described in the related issue
    - [ ]  New environment variables have been set
    - [ ]  New API services methods have tests
    - [ ]  Code errors are being logged in the code health service
- [ ]  **Product validation**
    - [ ]  UI changes look the same as in Figma
    - [ ]  Usage events are being sent to the product analytics service
    - [ ]  New common components have been documented in Storybook
    - [ ]  Preview link if it’s a customer facing issue
- [ ] **Documentation**
    - [ ] README updated
    - [ ] New API changes are documented
- [ ] **Accessibility**
    - [ ] UI changes are accessible

### CODE REVIEW

File: src/services/ProjectService.ts [hunk 1]
```diff
@@ -23,6 +24,10 @@ import { BudgetService } from './BudgetService'
 import { ProposalInCreation } from './ProposalService'
 import { VestingService } from './VestingService'
 
+function newestVestingFirst(a: TransparencyVesting, b: TransparencyVesting): number {
+  return new Date(b.vesting_start_at).getTime() - new Date(a.vesting_start_at).getTime()
```
Comment (1emu) [inline src/services/ProjectService.ts:28]: If dates are the same maybe you could check `vesting_finish_at` to see which one finishes later (only for those weird cases where both begin at the same time)

**Review by 1emu — APPROVED** [review]

**Review by 1emu — APPROVED** [review]

**Review by andyesp — APPROVED** [review]
